extends Node
class_name _Enum_DioJSONes


var ENUMS_TO_STRING = {
	 "BASE_GAME_DATA_PATH"        : BASE_GAME_DATA_PATH
	,"BASE_GAME_STABLE_DATA_PATH" : BASE_GAME_STABLE_DATA_PATH
	,"BASE_GAME_COMMUNITY_DATA_PATH" : BASE_GAME_COMMUNITY_DATA_PATH
	,"BASE_GAME_PERSONAL_DATA_PATH":BASE_GAME_PERSONAL_DATA_PATH
	,"FILEPATH_GAMEDATA_TILESETS":FILEPATH_GAMEDATA_TILESETS
}





const FILEPATH_GAMEDATA_TILESETS = "res://Gamedata/Tiled/TileSets/JSON"
const FILEPATH_LEC = "res://LECs"

const BASE_GAME_DATA_PATH           = "res://Gamedata/Game elements"
const BASE_GAME_STABLE_DATA_PATH    = BASE_GAME_DATA_PATH+"/Stable"
const BASE_GAME_COMMUNITY_DATA_PATH = BASE_GAME_DATA_PATH+"/Community"
const BASE_GAME_PERSONAL_DATA_PATH  = BASE_GAME_DATA_PATH+"/Personal"






